name: "auto push hexo to qiniu"
author: Yuan Jie (moogila@outlook.com)
description: "push the hexo static file to qiniu automatic."
inputs:
  bucket:
    description: "Name of the qiniu bucket"
    required: true
  access-key:
    description: "Access-key of qiniu"
    required: true
  secret-key:
    description: "Secret-key of qiniu"
    required: true
  hexo_cli_version:
    description: "The hexo cli version in your local env"
    required: true
    default: "4.3.0"
  domain:
    description: "Your website domain(http://example.com/)"
    required: true
  hexo-config-path:
    description: hexo config file path
    required: true
    default: "none"
  theme-config-path:
    description: theme config file
    required: true
    default: "none"
  theme-repostori:
    description: the repostory of theme
    required: false
    default: "none"
  qiniu-zone: 
    description: qiniu zone code
    required: true
    default: "none"
  theme-name:
    description: theme name
    required: true
    default: "theme"
  refresh-on: 
    description: upload all files
    required: true
    default: "no"


runs:
  using: "composite"
  steps:
    - name: setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - uses: actions/checkout@v3
      with:
        repository: DaxiLi/aja_hexo_push_action
        fetch-depth: 1
        path: blog

    - name: checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: source

    - name: checkout theme
      uses: actions/checkout@v3
      if: ${{ inputs.theme_repository }} != '' || ${{ inputs.theme_repository }} != 'none'
      with:
        repository: ${{inputs.theme_repository}}
        fetch-depth: 1
        path: theme

    - name: install dependencies
      run: npm ci
      shell: bash
      working-directory: blog

    - name: install dependencies
      run: npm ci
      shell: bash
      working-directory: blog/hexo

    - name: install hexo
      run: npm install -g hexo-cli@${{ inputs.hexo-cli-version }}
      shell: bash
      working-directory: blog

    - name: config
      run: |
        rm -rf blog/hexo/source && cp -rf source blog/hexo/
      shell: bash

    - if: ${{ inputs.theme_repository }} != '' || ${{ inputs.theme_repository }} != 'none'
      run: |
        rm -rf blog/hexo/themes/* && cp -rf theme blog/hexo/themes/${{inputs.theme_name}}
      shell: bash

    - name: move config
      if: ${{inputs.hexo_config_path}} != '' && ${{inputs.hexo_config_path}} != 'none'
      run: cp source/${{inputs.hexo_config_path}} blog/hexo/_config.yml
      shell: bash

    - if: ${{inputs.theme_config_path}} != '' && ${{inputs.theme_config_path}} != 'none'
      run: |
        cp -rf source/${{inputs.theme_config_path}}  blog/hexo/themes/${{inputs.theme_name}}/_config.yml
      shell: bash

    - name: clean ddirectory
      run: rm -rf blog/hexo/source/.github blog/hexo/source/.git
      shell: bash

    - name: generate public file
      run: hexo generate
      shell: bash
      working-directory: blog/hexo/

    - name: list  the generate files
      run: |
        ls blog/hexo/public  blog/hexo/themes  blog/hexo/themes/cards
      shell: bash

    - name: get manifest.json
      if: ${{inputs.domain}} != '' && ${{inputs.domain}} != 'none'
      run: wget --no-check-certificate ${{inputs.domain}}manifest.json -O ./manifest.json
      shell: bash

    - name: upload
      run: node blog/main.js ${{inputs.bucket}} ${{inputs.access_key}} ${{inputs.secret_key}} blog/hexo/public ${{inputs.domain}} ${{inputs.qiniu_zone}} ./manifest.json ${{inputs.refresh-on}}
      shell: bash
