name: manually push all hexo to qiniu
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: main
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: DaxiLi/aja_hexo_push_action@main
      with:
        bucket: your-bucket
        access-key: ${{ secrets.QINIU_ACCESS_KEY }}
        secret-key: ${{ secrets.QINIU_SECRET_KEY }}
        public-folder: your-hexo-public-folder(public)
        hexo-folder: your-hexo-folder(hexo)
        domain: your-domain(http://example.com)
        qiniu-zone: your-qiniu-zone

